ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/hako

    AddDefaultCharset Shift_JIS
    AddHandler cgi-script .cgi

    SetEnv PERL_USE_UNSAFE_INC 1

    <Directory /var/www/hako>
        Options +ExecCGI +FollowSymLinks
        AllowOverride None
        DirectoryIndex hako-main.cgi
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/hakoniwa-error.log
    CustomLog ${APACHE_LOG_DIR}/hakoniwa-access.log combined
</VirtualHost>
